const dummyStudents = [
  {
    _id: '6383338d20c1bb940a835b1a',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=0',
    firstName: 'Elisa',
    lastName: 'Gill',
    className: 10,
    gender: 'female',
    rollNumber: 17,
    email: 'elisagill@macronaut.com',
    message: 'You have a message from elisagill@macronaut.com',
  },
  {
    _id: '6383338d80533b6e9cf13289',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=1',
    firstName: 'Lowery',
    lastName: 'Alexander',
    className: 14,
    gender: 'male',
    rollNumber: 54,
    email: 'loweryalexander@macronaut.com',
    message: 'You have a message from loweryalexander@macronaut.com',
  },
  {
    _id: '6383338d68a6b5ba8227aac6',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=2',
    firstName: 'Guthrie',
    lastName: 'Carpenter',
    className: 15,
    gender: 'male',
    rollNumber: 48,
    email: 'guthriecarpenter@macronaut.com',
    message: 'You have a message from guthriecarpenter@macronaut.com',
  },
  {
    _id: '6383338d2b95987fc1a1559c',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=3',
    firstName: 'Kenya',
    lastName: 'Chan',
    className: 10,
    gender: 'female',
    rollNumber: 56,
    email: 'kenyachan@macronaut.com',
    message: 'You have a message from kenyachan@macronaut.com',
  },
  {
    _id: '6383338da12d6825fbb53f12',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=4',
    firstName: 'Farmer',
    lastName: 'Glass',
    className: 10,
    gender: 'male',
    rollNumber: 57,
    email: 'farmerglass@macronaut.com',
    message: 'You have a message from farmerglass@macronaut.com',
  },
  {
    _id: '6383338d31f1261aba002166',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=5',
    firstName: 'Hopkins',
    lastName: 'Boyer',
    className: 14,
    gender: 'male',
    rollNumber: 28,
    email: 'hopkinsboyer@macronaut.com',
    message: 'You have a message from hopkinsboyer@macronaut.com',
  },
  {
    _id: '6383338df2ad2757c66116c0',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=6',
    firstName: 'Alyson',
    lastName: 'Bush',
    className: 10,
    gender: 'female',
    rollNumber: 19,
    email: 'alysonbush@macronaut.com',
    message: 'You have a message from alysonbush@macronaut.com',
  },
  {
    _id: '6383338d2fac158b76dcb604',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=7',
    firstName: 'Briggs',
    lastName: 'Weeks',
    className: 14,
    gender: 'male',
    rollNumber: 46,
    email: 'briggsweeks@macronaut.com',
    message: 'You have a message from briggsweeks@macronaut.com',
  },
  {
    _id: '6383338da6695d15ce7ec005',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=8',
    firstName: 'Case',
    lastName: 'Sears',
    className: 12,
    gender: 'male',
    rollNumber: 45,
    email: 'casesears@macronaut.com',
    message: 'You have a message from casesears@macronaut.com',
  },
  {
    _id: '6383338da709376c3da95873',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=9',
    firstName: 'Maura',
    lastName: 'Kramer',
    className: 15,
    gender: 'female',
    rollNumber: 50,
    email: 'maurakramer@macronaut.com',
    message: 'You have a message from maurakramer@macronaut.com',
  },
  {
    _id: '6383338d001ee93894efd508',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=10',
    firstName: 'Blanca',
    lastName: 'Clarke',
    className: 13,
    gender: 'female',
    rollNumber: 59,
    email: 'blancaclarke@macronaut.com',
    message: 'You have a message from blancaclarke@macronaut.com',
  },
  {
    _id: '6383338dfd8a8de8cc2f8be4',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=11',
    firstName: 'Andrea',
    lastName: 'Stafford',
    className: 14,
    gender: 'female',
    rollNumber: 36,
    email: 'andreastafford@macronaut.com',
    message: 'You have a message from andreastafford@macronaut.com',
  },
  {
    _id: '6383338dda1501ae459eee2f',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=12',
    firstName: 'Ayers',
    lastName: 'Martinez',
    className: 13,
    gender: 'male',
    rollNumber: 51,
    email: 'ayersmartinez@macronaut.com',
    message: 'You have a message from ayersmartinez@macronaut.com',
  },
  {
    _id: '6383338d88609327a4b519a2',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=13',
    firstName: 'David',
    lastName: 'Howell',
    className: 16,
    gender: 'male',
    rollNumber: 46,
    email: 'davidhowell@macronaut.com',
    message: 'You have a message from davidhowell@macronaut.com',
  },
  {
    _id: '6383338d122f639011c83592',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=14',
    firstName: 'Frankie',
    lastName: 'Benjamin',
    className: 13,
    gender: 'female',
    rollNumber: 30,
    email: 'frankiebenjamin@macronaut.com',
    message: 'You have a message from frankiebenjamin@macronaut.com',
  },
  {
    _id: '6383338da72ab29e09def98e',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=15',
    firstName: 'Catalina',
    lastName: 'Randall',
    className: 11,
    gender: 'female',
    rollNumber: 58,
    email: 'catalinarandall@macronaut.com',
    message: 'You have a message from catalinarandall@macronaut.com',
  },
  {
    _id: '6383338d3f60854148fa102a',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=16',
    firstName: 'Wyatt',
    lastName: 'Fry',
    className: 11,
    gender: 'male',
    rollNumber: 39,
    email: 'wyattfry@macronaut.com',
    message: 'You have a message from wyattfry@macronaut.com',
  },
  {
    _id: '6383338d74df870e00f1b3f0',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=17',
    firstName: 'Jayne',
    lastName: 'Erickson',
    className: 13,
    gender: 'female',
    rollNumber: 57,
    email: 'jayneerickson@macronaut.com',
    message: 'You have a message from jayneerickson@macronaut.com',
  },
  {
    _id: '6383338d88be7484bca81b6d',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=18',
    firstName: 'Belinda',
    lastName: 'Chase',
    className: 13,
    gender: 'female',
    rollNumber: 35,
    email: 'belindachase@macronaut.com',
    message: 'You have a message from belindachase@macronaut.com',
  },
  {
    _id: '6383338d0675a97af98f0da2',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=19',
    firstName: 'Cabrera',
    lastName: 'Mercer',
    className: 15,
    gender: 'male',
    rollNumber: 47,
    email: 'cabreramercer@macronaut.com',
    message: 'You have a message from cabreramercer@macronaut.com',
  },
  {
    _id: '6383338d3623f0451f653c9a',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=20',
    firstName: 'Keri',
    lastName: 'Moreno',
    className: 10,
    gender: 'female',
    rollNumber: 58,
    email: 'kerimoreno@macronaut.com',
    message: 'You have a message from kerimoreno@macronaut.com',
  },
  {
    _id: '6383338d6e552d363dd9c36c',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=21',
    firstName: 'Aisha',
    lastName: 'Lawrence',
    className: 15,
    gender: 'female',
    rollNumber: 43,
    email: 'aishalawrence@macronaut.com',
    message: 'You have a message from aishalawrence@macronaut.com',
  },
  {
    _id: '6383338dfaa35651066b938d',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=22',
    firstName: 'Allie',
    lastName: 'Morris',
    className: 16,
    gender: 'female',
    rollNumber: 25,
    email: 'alliemorris@macronaut.com',
    message: 'You have a message from alliemorris@macronaut.com',
  },
  {
    _id: '6383338dd410b27f54887e93',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=23',
    firstName: 'Conner',
    lastName: 'Morrison',
    className: 12,
    gender: 'male',
    rollNumber: 45,
    email: 'connermorrison@macronaut.com',
    message: 'You have a message from connermorrison@macronaut.com',
  },
  {
    _id: '6383338d515bf63ab0788a71',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=24',
    firstName: 'Esperanza',
    lastName: 'Trevino',
    className: 12,
    gender: 'female',
    rollNumber: 47,
    email: 'esperanzatrevino@macronaut.com',
    message: 'You have a message from esperanzatrevino@macronaut.com',
  },
  {
    _id: '6383338d4b848043ec005e26',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=25',
    firstName: 'Isabelle',
    lastName: 'Mosley',
    className: 15,
    gender: 'female',
    rollNumber: 36,
    email: 'isabellemosley@macronaut.com',
    message: 'You have a message from isabellemosley@macronaut.com',
  },
  {
    _id: '6383338d93b243402a3e1e13',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=26',
    firstName: 'Pugh',
    lastName: 'Terrell',
    className: 16,
    gender: 'male',
    rollNumber: 31,
    email: 'pughterrell@macronaut.com',
    message: 'You have a message from pughterrell@macronaut.com',
  },
  {
    _id: '6383338d366a1e300dd1f4b5',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=27',
    firstName: 'Holt',
    lastName: 'Acevedo',
    className: 13,
    gender: 'male',
    rollNumber: 16,
    email: 'holtacevedo@macronaut.com',
    message: 'You have a message from holtacevedo@macronaut.com',
  },
  {
    _id: '6383338d22d3370e49f447ec',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=28',
    firstName: 'Roseann',
    lastName: 'Carlson',
    className: 11,
    gender: 'female',
    rollNumber: 23,
    email: 'roseanncarlson@macronaut.com',
    message: 'You have a message from roseanncarlson@macronaut.com',
  },
  {
    _id: '6383338d084ea9579eab4063',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=29',
    firstName: 'Koch',
    lastName: 'Oneil',
    className: 12,
    gender: 'male',
    rollNumber: 32,
    email: 'kochoneil@macronaut.com',
    message: 'You have a message from kochoneil@macronaut.com',
  },
  {
    _id: '6383338d6bea3f55fcad6c04',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=30',
    firstName: 'Virginia',
    lastName: 'Gamble',
    className: 12,
    gender: 'female',
    rollNumber: 38,
    email: 'virginiagamble@macronaut.com',
    message: 'You have a message from virginiagamble@macronaut.com',
  },
  {
    _id: '6383338deb24ad8853a2427e',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=31',
    firstName: 'Christensen',
    lastName: 'Ryan',
    className: 15,
    gender: 'male',
    rollNumber: 16,
    email: 'christensenryan@macronaut.com',
    message: 'You have a message from christensenryan@macronaut.com',
  },
  {
    _id: '6383338d4ebd5271be594525',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=32',
    firstName: 'Daniel',
    lastName: 'Mcfadden',
    className: 16,
    gender: 'male',
    rollNumber: 49,
    email: 'danielmcfadden@macronaut.com',
    message: 'You have a message from danielmcfadden@macronaut.com',
  },
  {
    _id: '6383338d28f5b49015e92f9b',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=33',
    firstName: 'Huffman',
    lastName: 'Garza',
    className: 12,
    gender: 'male',
    rollNumber: 55,
    email: 'huffmangarza@macronaut.com',
    message: 'You have a message from huffmangarza@macronaut.com',
  },
  {
    _id: '6383338d0fa671ed0d116837',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=34',
    firstName: 'Castro',
    lastName: 'Harrington',
    className: 11,
    gender: 'male',
    rollNumber: 23,
    email: 'castroharrington@macronaut.com',
    message: 'You have a message from castroharrington@macronaut.com',
  },
  {
    _id: '6383338d15c89beadcff565b',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=35',
    firstName: 'Reva',
    lastName: 'Jacobson',
    className: 12,
    gender: 'female',
    rollNumber: 15,
    email: 'revajacobson@macronaut.com',
    message: 'You have a message from revajacobson@macronaut.com',
  },
  {
    _id: '6383338dcde1ad6db87d9b3c',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=36',
    firstName: 'Benita',
    lastName: 'Bruce',
    className: 14,
    gender: 'female',
    rollNumber: 14,
    email: 'benitabruce@macronaut.com',
    message: 'You have a message from benitabruce@macronaut.com',
  },
  {
    _id: '6383338d92c7f32854cffe59',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=37',
    firstName: 'Buckley',
    lastName: 'Knowles',
    className: 16,
    gender: 'male',
    rollNumber: 31,
    email: 'buckleyknowles@macronaut.com',
    message: 'You have a message from buckleyknowles@macronaut.com',
  },
  {
    _id: '6383338d0b09e555467dbe2e',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=38',
    firstName: 'Concetta',
    lastName: 'Logan',
    className: 16,
    gender: 'female',
    rollNumber: 15,
    email: 'concettalogan@macronaut.com',
    message: 'You have a message from concettalogan@macronaut.com',
  },
  {
    _id: '6383338db64acf9c9f1c8d3d',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=39',
    firstName: 'Evangelina',
    lastName: 'Watts',
    className: 11,
    gender: 'female',
    rollNumber: 37,
    email: 'evangelinawatts@macronaut.com',
    message: 'You have a message from evangelinawatts@macronaut.com',
  },
  {
    _id: '6383338d31abe69346e78d0d',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=40',
    firstName: 'Patti',
    lastName: 'Puckett',
    className: 15,
    gender: 'female',
    rollNumber: 51,
    email: 'pattipuckett@macronaut.com',
    message: 'You have a message from pattipuckett@macronaut.com',
  },
  {
    _id: '6383338dc56664251865e65a',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=41',
    firstName: 'Tia',
    lastName: 'Fulton',
    className: 13,
    gender: 'female',
    rollNumber: 53,
    email: 'tiafulton@macronaut.com',
    message: 'You have a message from tiafulton@macronaut.com',
  },
  {
    _id: '6383338dd72980cbcdfbe77f',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=42',
    firstName: 'Charity',
    lastName: 'Cain',
    className: 13,
    gender: 'female',
    rollNumber: 24,
    email: 'charitycain@macronaut.com',
    message: 'You have a message from charitycain@macronaut.com',
  },
  {
    _id: '6383338dec82895bbff49627',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=43',
    firstName: 'Briana',
    lastName: 'Crosby',
    className: 10,
    gender: 'female',
    rollNumber: 50,
    email: 'brianacrosby@macronaut.com',
    message: 'You have a message from brianacrosby@macronaut.com',
  },
  {
    _id: '6383338dc75f3b63c1166c58',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=44',
    firstName: 'Nieves',
    lastName: 'Stephenson',
    className: 16,
    gender: 'male',
    rollNumber: 10,
    email: 'nievesstephenson@macronaut.com',
    message: 'You have a message from nievesstephenson@macronaut.com',
  },
  {
    _id: '6383338d3e903abbb1cde558',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=45',
    firstName: 'Miriam',
    lastName: 'Byers',
    className: 16,
    gender: 'female',
    rollNumber: 59,
    email: 'miriambyers@macronaut.com',
    message: 'You have a message from miriambyers@macronaut.com',
  },
  {
    _id: '6383338d19404f8cad7e601f',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=46',
    firstName: 'Helga',
    lastName: 'Pope',
    className: 12,
    gender: 'female',
    rollNumber: 52,
    email: 'helgapope@macronaut.com',
    message: 'You have a message from helgapope@macronaut.com',
  },
  {
    _id: '6383338deb98ee3267661c6c',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=47',
    firstName: 'Macias',
    lastName: 'Harvey',
    className: 11,
    gender: 'male',
    rollNumber: 55,
    email: 'maciasharvey@macronaut.com',
    message: 'You have a message from maciasharvey@macronaut.com',
  },
  {
    _id: '6383338dbc6d5d6a63a6836d',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=48',
    firstName: 'Josie',
    lastName: 'Preston',
    className: 16,
    gender: 'female',
    rollNumber: 14,
    email: 'josiepreston@macronaut.com',
    message: 'You have a message from josiepreston@macronaut.com',
  },
  {
    _id: '6383338d0bf38d42d0fc0e74',
    isActive: true,
    picture: 'https://i.pravatar.cc/300?img=49',
    firstName: 'Spence',
    lastName: 'Wall',
    className: 15,
    gender: 'male',
    rollNumber: 38,
    email: 'spencewall@macronaut.com',
    message: 'You have a message from spencewall@macronaut.com',
  },
];
export default dummyStudents;
